security:
    # Password hashing configuration
    password_hashers:
        App\Entity\User:
            algorithm: auto

    # User provider (load users from database using their email)
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    # Firewalls (authentication system config)
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            
            custom_authenticators:
                - App\Security\GoogleAuthenticator

            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                default_target_path: app_redirect_after_login # We’ll define this route

            logout:
                path: app_logout
                target: app_login

    # Access control rules
    access_control:
        - { path: ^/admin/dashboard, roles: ROLE_ADMIN }
        - { path: ^/agent/dashboard, roles: ROLE_AGENT }
        - { path: ^/client, roles: ROLE_CLIENT }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: PUBLIC_ACCESS }
        - { path: ^/contact, roles: ROLE_CLIENT }
        - { path: /reclamation, roles: [ROLE_AGENT, ROLE_ADMIN] }
        - { path: ^/connect/google, roles: PUBLIC_ACCESS }
        - { path: ^/connect/google/check, roles: PUBLIC_ACCESS }

