version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    environment:
      PORT: 8000
      APP_ENV: dev
      APP_SECRET: 1e22d742eb3048c4b09560a76ebdf272
      DATABASE_URL: mysql://root:root@db:3306/easytrip
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: easytrip_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: easytrip
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
