controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
# config/routes.yaml
connect_google_check:
    path: /connect/google/check
    controller: App\Controller\OAuthController::checkGoogle
